FROM ghcr.io/tight-eng/pg_track_events/agent:0.0.2-alpha.3@sha256:12eb427fb2bf0f649dfa129d2483ea25559e523cfd039814962142c63515c0db

COPY pg_track_events.config.yaml .

# Debug: List contents of /app directory
RUN ls -la /app
